use super::types::{CanonicalCommand, CommandClass, CommandFamily};

const fn command(
    family: CommandFamily,
    name: &'static str,
    class: CommandClass,
    summary: &'static str,
) -> CanonicalCommand {
    CanonicalCommand {
        family,
        command: name,
        class,
        summary,
    }
}

pub const CANONICAL_COMMANDS: &[CanonicalCommand] = &[
    command(
        CommandFamily::Help,
        "help",
        CommandClass::ReadOnly,
        "Show the available Neomax tool surface.",
    ),
    command(
        CommandFamily::Configuration,
        "config show",
        CommandClass::ReadOnly,
        "Show effective local settings.",
    ),
    command(
        CommandFamily::Configuration,
        "config set",
        CommandClass::Mutating,
        "Update a supported local setting.",
    ),
    command(
        CommandFamily::Dispatch,
        "dispatch",
        CommandClass::External,
        "Route work to an eligible orchestrator or worker.",
    ),
    command(
        CommandFamily::Accounts,
        "account status",
        CommandClass::ReadOnly,
        "Inspect account eligibility and usage state.",
    ),
    command(
        CommandFamily::Accounts,
        "account pause",
        CommandClass::Mutating,
        "Pause an account from automatic selection.",
    ),
    command(
        CommandFamily::Accounts,
        "account unpause",
        CommandClass::Mutating,
        "Allow a paused account to be selected again.",
    ),
    command(
        CommandFamily::Accounts,
        "account rotate",
        CommandClass::External,
        "Request account authentication rotation.",
    ),
    command(
        CommandFamily::Accounts,
        "pause",
        CommandClass::Mutating,
        "Pause an eligible account or orchestrator.",
    ),
    command(
        CommandFamily::Accounts,
        "unpause",
        CommandClass::Mutating,
        "Resume account or orchestrator selection.",
    ),
    command(
        CommandFamily::Git,
        "diff",
        CommandClass::ReadOnly,
        "Inspect project or worktree changes.",
    ),
    command(
        CommandFamily::Git,
        "subagent-diff",
        CommandClass::ReadOnly,
        "Inspect changes attributed to a worker.",
    ),
    command(
        CommandFamily::Git,
        "premerge",
        CommandClass::ReadOnly,
        "Check whether a change is ready for merge.",
    ),
    command(
        CommandFamily::Git,
        "clean",
        CommandClass::Destructive,
        "Remove selected generated worktree state.",
    ),
    command(
        CommandFamily::Git,
        "tidy",
        CommandClass::Destructive,
        "Remove stale generated state after confirmation.",
    ),
    command(
        CommandFamily::Git,
        "ls",
        CommandClass::ReadOnly,
        "List project and worktree entries.",
    ),
    command(
        CommandFamily::Issues,
        "issue",
        CommandClass::Mutating,
        "Inspect or update a coordinated issue record.",
    ),
    command(
        CommandFamily::Issues,
        "ci-sync",
        CommandClass::External,
        "Synchronize repository CI metadata.",
    ),
    command(
        CommandFamily::Issues,
        "ack",
        CommandClass::Mutating,
        "Acknowledge a coordinated issue event.",
    ),
    command(
        CommandFamily::Issues,
        "reconcile",
        CommandClass::Mutating,
        "Reconcile issue and repository state.",
    ),
    command(
        CommandFamily::Lifecycle,
        "resume",
        CommandClass::Mutating,
        "Resume a durable run.",
    ),
    command(
        CommandFamily::Lifecycle,
        "retry",
        CommandClass::Mutating,
        "Retry a failed run under current policy.",
    ),
    command(
        CommandFamily::Lifecycle,
        "kill",
        CommandClass::Destructive,
        "Stop a run and its owned processes.",
    ),
    command(
        CommandFamily::Lifecycle,
        "handoff",
        CommandClass::Mutating,
        "Transfer a run to another eligible worker.",
    ),
    command(
        CommandFamily::Lifecycle,
        "shepherd",
        CommandClass::Mutating,
        "Reconcile durable work and recovery state.",
    ),
    command(
        CommandFamily::Orchestration,
        "orchestrators",
        CommandClass::ReadOnly,
        "List available orchestrator profiles.",
    ),
    command(
        CommandFamily::Orchestration,
        "modes",
        CommandClass::ReadOnly,
        "Show supported orchestration modes.",
    ),
    command(
        CommandFamily::Orchestration,
        "pick-orch",
        CommandClass::Mutating,
        "Select an orchestrator for future work.",
    ),
    command(
        CommandFamily::Orchestration,
        "pick-neomax",
        CommandClass::Mutating,
        "Select universal provider routing.",
    ),
    command(
        CommandFamily::Orchestration,
        "orch-register",
        CommandClass::Mutating,
        "Register an orchestrator profile.",
    ),
    command(
        CommandFamily::Orchestration,
        "orch-unregister",
        CommandClass::Destructive,
        "Remove an orchestrator profile.",
    ),
    command(
        CommandFamily::Orchestration,
        "orch-on",
        CommandClass::Mutating,
        "Enable an orchestrator profile.",
    ),
    command(
        CommandFamily::Orchestration,
        "orient",
        CommandClass::ReadOnly,
        "Summarize the current project and routing context.",
    ),
    command(
        CommandFamily::Orchestration,
        "select",
        CommandClass::Mutating,
        "Select an orchestrator target for a handoff or future launch.",
    ),
    command(
        CommandFamily::Orchestration,
        "why",
        CommandClass::ReadOnly,
        "Explain the current orchestrator selection decision.",
    ),
    command(
        CommandFamily::Orchestration,
        "run-all",
        CommandClass::External,
        "Run eligible work across configured providers.",
    ),
    command(
        CommandFamily::Orchestration,
        "rotate",
        CommandClass::External,
        "Rotate the active orchestrator or account.",
    ),
    command(
        CommandFamily::Orchestration,
        "rotate-tick",
        CommandClass::External,
        "Advance an automatic rotation cycle.",
    ),
    command(
        CommandFamily::Orchestration,
        "solo-rotate",
        CommandClass::External,
        "Rotate the selected solo orchestrator.",
    ),
    command(
        CommandFamily::Orchestration,
        "solo-setup",
        CommandClass::External,
        "Set up a solo orchestrator session.",
    ),
    command(
        CommandFamily::Projects,
        "projects",
        CommandClass::ReadOnly,
        "List portable projects.",
    ),
    command(
        CommandFamily::Projects,
        "project-register",
        CommandClass::Mutating,
        "Register the current project.",
    ),
    command(
        CommandFamily::Projects,
        "project-unregister",
        CommandClass::Destructive,
        "Remove a project registration.",
    ),
    command(
        CommandFamily::Queue,
        "queue",
        CommandClass::Mutating,
        "Inspect or update durable work allocation.",
    ),
    command(
        CommandFamily::Sessions,
        "sessions",
        CommandClass::ReadOnly,
        "List active and historical sessions.",
    ),
    command(
        CommandFamily::Sessions,
        "session-rotate",
        CommandClass::External,
        "Rotate a live session to an eligible account.",
    ),
    command(
        CommandFamily::Sessions,
        "subagents",
        CommandClass::ReadOnly,
        "Inspect worker and subagent activity.",
    ),
    command(
        CommandFamily::Sessions,
        "portal",
        CommandClass::ReadOnly,
        "Inspect the shared local usage and session portal.",
    ),
    command(
        CommandFamily::Tasks,
        "tasks",
        CommandClass::ReadOnly,
        "List durable project tasks.",
    ),
    command(
        CommandFamily::Tasks,
        "task",
        CommandClass::Mutating,
        "Create or update a durable task.",
    ),
    command(
        CommandFamily::Usage,
        "usage",
        CommandClass::ReadOnly,
        "Inspect usage, quotas, and routing eligibility.",
    ),
    command(
        CommandFamily::Usage,
        "usage-watch",
        CommandClass::External,
        "Collect provider usage in the background.",
    ),
    command(
        CommandFamily::Usage,
        "keepalive",
        CommandClass::Mutating,
        "Maintain eligible sessions and account state.",
    ),
    command(
        CommandFamily::Workers,
        "log",
        CommandClass::ReadOnly,
        "Inspect worker and run logs.",
    ),
    command(
        CommandFamily::Workers,
        "audit",
        CommandClass::ReadOnly,
        "Inspect routing, state, and configuration invariants.",
    ),
    command(
        CommandFamily::Workers,
        "find",
        CommandClass::ReadOnly,
        "Find runs, tasks, projects, or issues.",
    ),
    command(
        CommandFamily::Workers,
        "history",
        CommandClass::ReadOnly,
        "Inspect durable run history.",
    ),
    command(
        CommandFamily::Workers,
        "status",
        CommandClass::ReadOnly,
        "Inspect current run and worker status.",
    ),
    command(
        CommandFamily::Workers,
        "paused",
        CommandClass::ReadOnly,
        "Inspect paused accounts and orchestrators.",
    ),
    command(
        CommandFamily::Workers,
        "rotate-auth",
        CommandClass::External,
        "Request authentication rotation for a worker.",
    ),
    command(
        CommandFamily::Workers,
        "pr",
        CommandClass::External,
        "Prepare or update a pull request workflow.",
    ),
    command(
        CommandFamily::Workers,
        "turn-hook",
        CommandClass::External,
        "Run a configured turn hook.",
    ),
    command(
        CommandFamily::Workers,
        "model-guard",
        CommandClass::External,
        "Validate model policy before a worker turn.",
    ),
    command(
        CommandFamily::Workers,
        "usage-hook",
        CommandClass::External,
        "Run a configured usage hook.",
    ),
    command(
        CommandFamily::Configuration,
        "install",
        CommandClass::Destructive,
        "Install or upgrade the managed Neomax command surface.",
    ),
    command(
        CommandFamily::Configuration,
        "uninstall",
        CommandClass::Destructive,
        "Remove the managed Neomax command surface.",
    ),
];
